clone:
  git:
    image: plugins/git
    branch: origin
    tags: true

pipeline:

  build:
    image: node:12-alpine
    commands:
      - npm install
      - npm run build
    when:
      event: [push, tag, pull_request]

  aerokube_website_push:
    image: golang:1.12.5
    commands:
      - ./deploy.sh
    secrets: [ github_token ]
    when:
      event: [tag]
