baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Aerokube | Efficient Test Automation Infrastructure"

enableRobotsTXT = true

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
description = "We deliver lightning fast and efficient test automation infrastructure: Moon for running browsers in Kubernetes, Moon Cloud - online browser automation platform and Boot for launching lightweight virtual machiens for test automation and software development. Our solutions support Selenium, Playwright, Cypress and Puppeteer out of the box."
