baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Aerokube | Efficient Browser Automation Infrastructure"

enableRobotsTXT = true

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
description = "We deliver lightning fast and efficient browser automation infrastructure: Selenoid for Docker, Moon for Kubernetes and Moon Cloud - online browser automation platform. Our solutions support Selenium, Playwright, Cypress and Puppeteer out of the box."
